/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.dontesta.labs.services.temperature.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Temperature service. Represents a row in the &quot;DNTLABS_Temperature&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.dontesta.labs.services.temperature.model.impl.TemperatureModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.dontesta.labs.services.temperature.model.impl.TemperatureImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Temperature
 * @generated
 */
@ProviderType
public interface TemperatureModel
	extends BaseModel<Temperature>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a temperature model instance should use the {@link Temperature} interface instead.
	 */

	/**
	 * Returns the primary key of this temperature.
	 *
	 * @return the primary key of this temperature
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this temperature.
	 *
	 * @param primaryKey the primary key of this temperature
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this temperature.
	 *
	 * @return the uuid of this temperature
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this temperature.
	 *
	 * @param uuid the uuid of this temperature
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the temperature ID of this temperature.
	 *
	 * @return the temperature ID of this temperature
	 */
	public long getTemperatureId();

	/**
	 * Sets the temperature ID of this temperature.
	 *
	 * @param temperatureId the temperature ID of this temperature
	 */
	public void setTemperatureId(long temperatureId);

	/**
	 * Returns the group ID of this temperature.
	 *
	 * @return the group ID of this temperature
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this temperature.
	 *
	 * @param groupId the group ID of this temperature
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this temperature.
	 *
	 * @return the company ID of this temperature
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this temperature.
	 *
	 * @param companyId the company ID of this temperature
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this temperature.
	 *
	 * @return the user ID of this temperature
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this temperature.
	 *
	 * @param userId the user ID of this temperature
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this temperature.
	 *
	 * @return the user uuid of this temperature
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this temperature.
	 *
	 * @param userUuid the user uuid of this temperature
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this temperature.
	 *
	 * @return the user name of this temperature
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this temperature.
	 *
	 * @param userName the user name of this temperature
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this temperature.
	 *
	 * @return the create date of this temperature
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this temperature.
	 *
	 * @param createDate the create date of this temperature
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this temperature.
	 *
	 * @return the modified date of this temperature
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this temperature.
	 *
	 * @param modifiedDate the modified date of this temperature
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the device ID of this temperature.
	 *
	 * @return the device ID of this temperature
	 */
	@AutoEscape
	public String getDeviceId();

	/**
	 * Sets the device ID of this temperature.
	 *
	 * @param deviceId the device ID of this temperature
	 */
	public void setDeviceId(String deviceId);

	/**
	 * Returns the value of this temperature.
	 *
	 * @return the value of this temperature
	 */
	public int getValue();

	/**
	 * Sets the value of this temperature.
	 *
	 * @param value the value of this temperature
	 */
	public void setValue(int value);

	/**
	 * Returns the status of this temperature.
	 *
	 * @return the status of this temperature
	 */
	public int getStatus();

	/**
	 * Sets the status of this temperature.
	 *
	 * @param status the status of this temperature
	 */
	public void setStatus(int status);

}