/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.dontesta.labs.services.temperature.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import it.dontesta.labs.services.temperature.model.Temperature;
import it.dontesta.labs.services.temperature.model.TemperatureModel;
import it.dontesta.labs.services.temperature.model.TemperatureSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Temperature service. Represents a row in the &quot;DNTLABS_Temperature&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TemperatureModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TemperatureImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TemperatureImpl
 * @see Temperature
 * @see TemperatureModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TemperatureModelImpl extends BaseModelImpl<Temperature>
	implements TemperatureModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a temperature model instance should use the {@link Temperature} interface instead.
	 */
	public static final String TABLE_NAME = "DNTLABS_Temperature";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "temperatureId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "deviceId", Types.VARCHAR },
			{ "value", Types.INTEGER },
			{ "status", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("temperatureId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("deviceId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table DNTLABS_Temperature (uuid_ VARCHAR(75) null,temperatureId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,deviceId VARCHAR(75) null,value INTEGER,status INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table DNTLABS_Temperature";
	public static final String ORDER_BY_JPQL = " ORDER BY temperature.deviceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY DNTLABS_Temperature.deviceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(it.dontesta.labs.services.temperature.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.it.dontesta.labs.services.temperature.model.Temperature"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(it.dontesta.labs.services.temperature.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.it.dontesta.labs.services.temperature.model.Temperature"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(it.dontesta.labs.services.temperature.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.it.dontesta.labs.services.temperature.model.Temperature"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long DEVICEID_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long STATUS_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Temperature toModel(TemperatureSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Temperature model = new TemperatureImpl();

		model.setUuid(soapModel.getUuid());
		model.setTemperatureId(soapModel.getTemperatureId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDeviceId(soapModel.getDeviceId());
		model.setValue(soapModel.getValue());
		model.setStatus(soapModel.getStatus());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Temperature> toModels(TemperatureSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Temperature> models = new ArrayList<Temperature>(soapModels.length);

		for (TemperatureSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(it.dontesta.labs.services.temperature.service.util.ServiceProps.get(
				"lock.expiration.time.it.dontesta.labs.services.temperature.model.Temperature"));

	public TemperatureModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _temperatureId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTemperatureId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _temperatureId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Temperature.class;
	}

	@Override
	public String getModelClassName() {
		return Temperature.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("temperatureId", getTemperatureId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("deviceId", getDeviceId());
		attributes.put("value", getValue());
		attributes.put("status", getStatus());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long temperatureId = (Long)attributes.get("temperatureId");

		if (temperatureId != null) {
			setTemperatureId(temperatureId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String deviceId = (String)attributes.get("deviceId");

		if (deviceId != null) {
			setDeviceId(deviceId);
		}

		Integer value = (Integer)attributes.get("value");

		if (value != null) {
			setValue(value);
		}

		Integer status = (Integer)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTemperatureId() {
		return _temperatureId;
	}

	@Override
	public void setTemperatureId(long temperatureId) {
		_temperatureId = temperatureId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDeviceId() {
		if (_deviceId == null) {
			return StringPool.BLANK;
		}
		else {
			return _deviceId;
		}
	}

	@Override
	public void setDeviceId(String deviceId) {
		_columnBitmask = -1L;

		if (_originalDeviceId == null) {
			_originalDeviceId = _deviceId;
		}

		_deviceId = deviceId;
	}

	public String getOriginalDeviceId() {
		return GetterUtil.getString(_originalDeviceId);
	}

	@JSON
	@Override
	public int getValue() {
		return _value;
	}

	@Override
	public void setValue(int value) {
		_value = value;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Temperature.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Temperature.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Temperature toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Temperature)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TemperatureImpl temperatureImpl = new TemperatureImpl();

		temperatureImpl.setUuid(getUuid());
		temperatureImpl.setTemperatureId(getTemperatureId());
		temperatureImpl.setGroupId(getGroupId());
		temperatureImpl.setCompanyId(getCompanyId());
		temperatureImpl.setUserId(getUserId());
		temperatureImpl.setUserName(getUserName());
		temperatureImpl.setCreateDate(getCreateDate());
		temperatureImpl.setModifiedDate(getModifiedDate());
		temperatureImpl.setDeviceId(getDeviceId());
		temperatureImpl.setValue(getValue());
		temperatureImpl.setStatus(getStatus());

		temperatureImpl.resetOriginalValues();

		return temperatureImpl;
	}

	@Override
	public int compareTo(Temperature temperature) {
		int value = 0;

		value = getDeviceId().compareTo(temperature.getDeviceId());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Temperature)) {
			return false;
		}

		Temperature temperature = (Temperature)obj;

		long primaryKey = temperature.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TemperatureModelImpl temperatureModelImpl = this;

		temperatureModelImpl._originalUuid = temperatureModelImpl._uuid;

		temperatureModelImpl._originalGroupId = temperatureModelImpl._groupId;

		temperatureModelImpl._setOriginalGroupId = false;

		temperatureModelImpl._originalCompanyId = temperatureModelImpl._companyId;

		temperatureModelImpl._setOriginalCompanyId = false;

		temperatureModelImpl._setModifiedDate = false;

		temperatureModelImpl._originalDeviceId = temperatureModelImpl._deviceId;

		temperatureModelImpl._originalStatus = temperatureModelImpl._status;

		temperatureModelImpl._setOriginalStatus = false;

		temperatureModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Temperature> toCacheModel() {
		TemperatureCacheModel temperatureCacheModel = new TemperatureCacheModel();

		temperatureCacheModel.uuid = getUuid();

		String uuid = temperatureCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			temperatureCacheModel.uuid = null;
		}

		temperatureCacheModel.temperatureId = getTemperatureId();

		temperatureCacheModel.groupId = getGroupId();

		temperatureCacheModel.companyId = getCompanyId();

		temperatureCacheModel.userId = getUserId();

		temperatureCacheModel.userName = getUserName();

		String userName = temperatureCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			temperatureCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			temperatureCacheModel.createDate = createDate.getTime();
		}
		else {
			temperatureCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			temperatureCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			temperatureCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		temperatureCacheModel.deviceId = getDeviceId();

		String deviceId = temperatureCacheModel.deviceId;

		if ((deviceId != null) && (deviceId.length() == 0)) {
			temperatureCacheModel.deviceId = null;
		}

		temperatureCacheModel.value = getValue();

		temperatureCacheModel.status = getStatus();

		return temperatureCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", temperatureId=");
		sb.append(getTemperatureId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", deviceId=");
		sb.append(getDeviceId());
		sb.append(", value=");
		sb.append(getValue());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("it.dontesta.labs.services.temperature.model.Temperature");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>temperatureId</column-name><column-value><![CDATA[");
		sb.append(getTemperatureId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deviceId</column-name><column-value><![CDATA[");
		sb.append(getDeviceId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Temperature.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Temperature.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _temperatureId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _deviceId;
	private String _originalDeviceId;
	private int _value;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _columnBitmask;
	private Temperature _escapedModel;
}